name: Telegram News MHTML

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: telegram-news
  cancel-in-progress: true

jobs:
  news:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Create temp folder
        run: mkdir -p temp

      - name: Run Bot
        env:
          BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
          BALE_CHAT_ID: ${{ secrets.BALE_CHAT_ID }}
        run: npm start

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: telegram-news
          path: |
            temp/**
            state.json

      - name: Commit state.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add state.json

          git diff --cached --quiet || git commit -m "Update state"

          git push
